version: "3"

services:
  api:
    build: .
    depends_on:
      - mongo
    environment:
      - PORT=5000
      - MONGODB_CNN=mongodb://mongo:27017/capas
    ports:
      - "5000:5000"
  mongo:
    image: mongo